### ISSUE TITLE
The "join()" should be called before the "worker" thread terminates

### ISSUE THREAD

**Issue by rumia-san** [ParkerD559/disperse#8]
Hi, ParkerD559
I have compiled your code and run the program. Everything works well until I tried "Quit" in the tray menu. Then the program prints "**terminate called without an active exception**” and crashed.

![1](https://user-images.githubusercontent.com/51704722/71586040-b78d6b80-2b53-11ea-9f59-8dc6f9927d4b.png)

This is because the main thread terminated while the worker thread is still running. Then the thread destructor will be called. However, the thread is still joinable(), and terminate() will be called, which leads to this issue.
**The join() method should be called before the worker thread is destructed.**

Reference: https://stackoverflow.com/questions/7381757/c-terminate-called-without-an-active-exception

Here is my fix:
```
std::atomic<bool> quit(false);

void workerMain() {
    while (true) {
        mutex.lock();
        if (!queue.empty()) {
            Tailor::command command = queue.front();
            queue.pop();
            Tailor::alter(command);
        }
        mutex.unlock();
        API::sleep(50);
        if(quit) {
            break;
        }
    }
}
Worker::~Worker() {
    quit = true;
    this->thread_obj.join();
}
```
I use a atomic bool to escape the loop, and call join() in Worker::~Worker()

**Comment by dparker2** [comment]
Fixed by #9

Thanks :)
